# Generated by Django 4.1.7 on 2023-06-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hacka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('BackGround_Image', models.ImageField(upload_to='')),
                ('Hackathon_Image', models.ImageField(upload_to='')),
                ('Type', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'IMAGE'), ('LINK', 'LINK')], default='LINK', max_length=50)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Reward_Prize', models.IntegerField()),
            ],
        ),
    ]
