# Generated by Django 4.1.7 on 2023-06-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hack', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacka',
            name='Registered_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Hack.user'),
        ),
    ]
