# Generated by Django 4.1.7 on 2023-06-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hack', '0006_alter_hacka_registered_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacka',
            name='Registered_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hacks', to='Hack.user'),
        ),
    ]
