# Generated by Django 4.1.7 on 2023-06-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hack', '0007_alter_hacka_registered_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacka',
            name='Registered_to',
        ),
        migrations.AddField(
            model_name='user',
            name='Registered_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Hacks', to='Hack.hacka'),
        ),
    ]
